language: node_js
node_js:
  - "5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
install:
  - npm install
script:
  - npm test
after_script: "npm install coveralls@2.10.0 && cat ./coverage/*/lcov.info | coveralls"