sudo: false
language: node_js
node_js:
  - "5.0"
  - "6.0"
  - "7.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - develop
npm_skip_install:

before_install:
  - npm install yarn -g
  - yarn
before_script:
  - npm prune
script:
  - npm test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run coveralls